repos:
-   repo: local
    hooks:
    -   id: isort 
        name: isort 📚
        entry: zsh -c 'isort .'
        language: system
        always_run: true
        pass_filenames: true
    -   id: needs-hash
        name: commit message needs issues
        language: pygrep
        entry: '#\d+'
        args: [--multiline, --negate]
        stages: [commit-msg]
    -   id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
