repos:
-   repo: local
    hooks:
    -   id: needs-changelog
        name: commit message needs "Changelog:"
        language: pygrep
        entry: '^Changelog:'
        args: [--multiline, --negate]
        stages: [commit-msg]
        always_run: true
    -   id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
