repos:
-   repo: local
    hooks:
    -   id: pytest-check
        stages: [commit]
        types: [python]
        name: pytest-check
        entry: python -m pytest
        language: system
        pass_filenames: false
        always_run: true
    -   id: needs-issue
        name: commit message needs to reference an issue"
        language: pygrep
        entry: '#\d+'
        args: [--multiline, --negate]
        stages: [commit-msg]