# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
      - run: |
          gh release create ${{ github.ref }} release.tar.xz
    env:
      GITHUB_TOKEN: ${{ github.TOKEN }}
    name: Creates a release in GitHub and uploads attachments