name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish release
      id: publish-release
      uses: ghalactic/github-release-from-tag@v5
      with:
         prerelease: "false"
         reactions: heart,rocket,eyes

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install pyinstaller
      run: pip install pyinstaller

    - name: Build for Windows
      run: pyinstaller -F --add-data "templates;templates" --add-data "helper.py;." main.py

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: Fhwang0926/upload-release-asset@v1.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.publish-release.outputs.upload_url }}
        asset_name: ./dist/main.exe
        asset_label: latest