name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: set lower case owner name
      id: lowercase_username
      run: |
        echo "${OWNER,,}"
      env:
        OWNER: '${{ github.repository_owner }}'
      shell: bash

    - name: Build the Docker image
      run: |
            docker build . --tag ghcr.io/${{ steps.lowercase_username.outputs.lowercase_username }}/${{ github.event.repository.name }}:latest
            docker run ghcr.io/${{ steps.lowercase_username.outputs.lowercase_username }}/${{ github.event.repository.name }}:latest
            docker push ghcr.io/${{ steps.lowercase_username.outputs.lowercase_username }}/${{ github.event.repository.name }}:latest