name: Release from tag

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish release
      id: publish-release
      uses: ghalactic/github-release-from-tag@v5
      with:
         prerelease: "false"
         reactions: heart,rocket,eyes

    - name: Create Executable
      uses: sayyid5416/pyinstaller@v1
      with:
        python_ver: '3.11'
        spec: 'main.spec'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'zu-bbbearbeiten.exe'
        options: --onefile

    - name: Upload Release Asset
      id: upload-release-asset
      uses: Fhwang0926/upload-release-asset@v1.1.8
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.publish-release.outputs.upload_url }}
        asset_name: ./dist/zu-bbbearbeiten.exe
        asset_label: latest
